### ISSUE TITLE
1.6.0 fails to start even though VM appears to be up

### ISSUE THREAD

**Issue by ndarilek** [boot2docker/windows-installer#101]
Boot2Docker-cli version: v1.6.0
Git commit: 9894ae9
2015/04/16 22:51:10 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2015/04/16 22:51:11 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountPrefix /
2015/04/16 22:51:11 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountDir /
2015/04/16 22:51:12 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe sharedfolder add boot2docker-vm --name c/Users --hostpath C:\Users --automount
VBoxManage.exe: error: Shared folder named 'c/Users' already exists
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostpath).raw(), fWritable, fAutoMount)" at line 1008 of file VBoxManageMisc.cpp
2015/04/16 22:51:12 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe setextradata boot2docker-vm VBoxInternal2/SharedFoldersEnableSymlinksCreate/c/Users 1
2015/04/16 22:51:12 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm boot2docker-vm --type headless
Waiting for VM "boot2docker-vm" to power on...
VM "boot2docker-vm" has been successfully started.
error in run: Failed to start machine "boot2docker-vm": exit status 1

Interestingly, `boot2docker status` still claims poweroff state.

**Comment by ahmetalpbalkan** [comment]
@ndarilek can you please run the command 

    boot2docker up -v

and paste the output here?

**Comment by ndarilek** [comment]
I already have, the bug report is a `up -v` transcript.

I did seem to fix the issue by uninstalling/reinstalling VirtualBox. I had an older version installed. I forget, does the Boot2Docker installer install VirtualBox as well? If so, maybe there was an issue running the upgrade of the old install? We can close this if digging deeper into what may have failed isn't worthwhile, but the failure persisted across several reboots and didn't go away until the reinstall of VB.

**Comment by ahmetalpbalkan** [comment]
@ndarilek yeah it looks like external dependencies like VirtualBox and Git are causing various issues on various installations. I'm not even sure if it's a version problem or a config issue. We're seeing similar issues at #102.

@ndarilek if you run the Boot2Docker installer again, you'll see that the install checkbox next to VirtualBox is unchecked if any VirtualBox installation exists on the system at that time. If not checked, it doesn't install vbox. If it is checked, then it installs the vbox version bundled with the B2D installer MSI. (see [this code](https://github.com/boot2docker/windows-installer/blob/8b508882bf06c19e70d02a63e773a4b1d09fdbc5/bundle.sh#L10))

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
