### ISSUE TITLE
v1.6.0: “line 36: cd: HOME not set” in start.sh running Boot2Docker

### ISSUE THREAD

**Issue by bwoolf1** [boot2docker/windows-installer#102]
I have installed Docker on my Windows laptop using Docker for Windows Installer v1.6.0. When I ran the `start.sh` script for the first time, it initializes and starts the VM, but then the script gives the error "line 36: cd: HOME not set" and exits:

```
C:\Program Files\Boot2Docker for Windows>start.sh

initializing...

starting...
Waiting for VM and Docker daemon to start...
............................oooooooo
Started.
Writing C:\Users\Administrator\.boot2docker\certs\boot2docker-vm\ca.pem
Writing C:\Users\Administrator\.boot2docker\certs\boot2docker-vm\cert.pem
Writing C:\Users\Administrator\.boot2docker\certs\boot2docker-vm\key.pem

To connect the Docker client to the Docker daemon, please set:
    export DOCKER_CERT_PATH='C:\Users\Administrator\.boot2docker\certs\boot2docker-vm'
    export DOCKER_TLS_VERIFY=1
    export DOCKER_HOST=tcp://192.168.59.103:2376


IP address of docker VM:
192.168.59.103

setting environment variables ...
Writing C:\Users\Administrator\.boot2docker\certs\boot2docker-vm\ca.pem
Writing C:\Users\Administrator\.boot2docker\certs\boot2docker-vm\cert.pem
Writing C:\Users\Administrator\.boot2docker\certs\boot2docker-vm\key.pem
    export DOCKER_HOST=tcp://192.168.59.103:2376
    export DOCKER_CERT_PATH='C:\\Users\\Administrator\\.boot2docker\\certs\\boot2docker-vm'
    export DOCKER_TLS_VERIFY=1

You can now use `docker` directly, or `boot2docker ssh` to log into the VM.
C:\Program Files\Boot2Docker for Windows\start.sh: line 36: cd: HOME not set

C:\Program Files\Boot2Docker for Windows>
```

Lines 36 and 37 of the script are:

```
cd
exec "$BASH" --login -i
```

I've had to make some changes to the install to get this far:
- When `start.sh` opened WordPad, I made `C:\Program Files (x86)\Git\bin\sh.exe` Windows' default program for `.sh` files
- When `start.sh` encountered the error "line 5: clear: command not found", I added `C:\Program Files (x86)\Git\bin` to my system's path
- When the VM failed to start with "error in run: Failed to start machine "boot2docker-vm": exit status 1", I ran `boot2docker delete` and `boot2docker download` to delete the VM and download the ISO again

Now I'm stuck on the error "line 36: cd: HOME not set" in `start.sh`.

Any help would be appreciated. Thanks.

**Comment by mpas** [comment]
I am having the same problem. Stuck on line 36.. any solution to this?

**Comment by duglin** [comment]
@mpas did you have *.sh files associated with a certain program prior to running b2d?

**Comment by duglin** [comment]
ping @ahmetalpbalkan 
For another data point... I tried to install it and it brought up notepad when tried to run the sh files.  After I manually associated sh files with git's bash it then complained about not being able to find 'clean'.

**Comment by bwoolf1** [comment]
Today, I've reproduced the same experience from Friday: I uninstalled Docker (and Virtual Box and Git), made sure none of those were in my system path, and that there was no default program associated with the .sh file extension. Even under those circumstances, the install still isn't working.

Because there was no default .sh program, that got set to use <Git Home>/bin/sh.exe. So start.sh runs, but it still errors with "line 5: clear: command not found", as @duglin ran into. Adding git/bin to the system path once again fixed that, but if this is needed, it should be done by the installer. Again, the VM wouldn't start, exit status 1; I deleted the VM but didn't re-download the ISO. Running start.sh again created a new VM from the installed ISO and that one runs; why does the installer create a VM that won't start? Now that start.sh can start the VM, it is back to complaining "HOME not set". So I'm back to where I was on Friday.

On Stackoverflow, Nathaniel Waisbrot says the lines that are failing are restarting Bash and explains how to do that manually. If I start another shell to do that, I need to manually run the script's command to define the environment variables.

I'd like to know what I need to fix in Windows or the Docker install to get start.sh to run completely.

**Comment by ahmetalpbalkan** [comment]
@tianon any ideas how $HOME might not be set in msys in the first place?

**Comment by bwoolf1** [comment]
@ahmetalpbalkan: I did have Git SCM installed, but that was several uninstalls ago! I have uninstalled, made sure git/bin wasn't in my system path, and made sure there was no default program associated with .sh (such as WordPad). I then reinstalled, which just uses defaults. Are there any configuration preferences that Git's uninstaller doesn't install? If so, where are those, I can delete them manually and reinstall. Thanks for your help.

**Comment by ahmetalpbalkan** [comment]
@bwoolf1 actually I haven't done many clean installations. I don't think we changed anything during 1.6.0 that might cause:

1. `clean` to not exist
2. `PATH` is not set
3. `.sh` not associated with Git Bash

(although I must admit I've seen (3) happening on a clean install on a Windows 10 Preview machine). So another set of questions:

- Have you installed boot2docker before?
- Did you choose "Reboot" option after installation? (I didn't maybe that's why (2) and (3) might be happening.

**Comment by mpas** [comment]
@duglin my *.sh files where associated with SublimeText so i needed to change that. I did some digging around and had to comment out line 36 containing the 'cd' to get stuff working.

**Comment by duglin** [comment]
@ahmetalpbalkan I didn't reboot - will try again later when I get access to the machine again, but if that's required we should probably not make it optional and tell people they *must* reboot after installation.

**Comment by ahmetalpbalkan** [comment]
@mpas I don't know how we can force the file association (or if we should). Does your "Start Boot2Docker" link works if start.sh is associated with sublime or does it just start sublime? If that's the case we may change `.lnk` shortcuts to start like `c:\program files (x86)\Git\bin\bash.exe start.sh` maybe. @tianon

**Comment by mpas** [comment]
@ahmetalpbalkan When the .sh files are associated with SublimeText it just opens SublimeText with the contents of the start.sh file. I manually changed the association so this is not a problem for me. The .lnk shortcut could be a nice solution i guess!

**Comment by duglin** [comment]
@ahmetalpbalkan is rewriting the sh files in go an option?

**Comment by ahmetalpbalkan** [comment]
@duglin hmm @tianon is the authority there. :)

**Comment by mpas** [comment]
In my current setup the  start.sh script complains that the $HOME is not set.

Console output:
You can now use `docker` directly, or `boot2docker ssh` to log into the VM.
/c/Program Files/Boot2Docker for Windows/start.sh: line 37: cd: HOME not set
bash.exe"-3.1$

What would be the normal setting for $HOME?

**Comment by ahmetalpbalkan** [comment]
@mpas it would be `/c/Users/yourusername`

Can you please launch "Git Bash" shortcut and paste the output for `env` command to a gist?

**Comment by mpas** [comment]
@ahmetalpbalkan No problem! You can find it here https://gist.github.com/mpas/430058a167a360a80875

**Comment by ahmetalpbalkan** [comment]
@mpas looks like something is wrong with your git installation. Can you please upgrade your git installation from here http://www.git-scm.com/downloads and see if HOME is still missing from `env` in Git Bash?

**Comment by mpas** [comment]
I upgraded the git installation, restarted and checked the output of the env in bash. The HOME is still missing.

**Comment by bwoolf1** [comment]
@mpas: Not just a glitch on your side. I'm running into it, as is @duglin.

@ahmetalpbalkan: Looks like Git is not installing correctly, perhaps after an uninstall, and that's messing up Docker/Boot2Docker.

I've been able to get Docker working using boot2docker/windows-installer v1.5.0 (though with problems I had to manually fix; see https://developer.ibm.com/bluemix/2015/04/16/installing-docker-windows-fixes-common-problems/). I have NOT been able to get Docker running using installer v1.6.0.

**Comment by mpas** [comment]
I did a complete reinstall of Boot2Docker 1.6 including first removal of everything related and then reinstalling all including VirtualBox etc. This is not working as expected. The file association to .sh does not work and i am also experiencing other issues like not being able to mount a host folder as mentioned in https://github.com/boot2docker/boot2docker/issues/846.

**Comment by sceee** [comment]
I experienced the same issue ("line 36: cd: HOME not set" in start.sh) and found a fix - at least for my configuration.
I had TortoiseGit (coupled with msysgit 1.9.5) installed prior to installing Boot2Docker. In the msysgit installation while installing TortoiseGit, I think I may not have checked the "associate .sh files with git bash".

I then manually reinstalled msysgit from https://msysgit.github.io/ and choose to "associate .sh files with git bash". After this, Boot2Docker worked and the "HOME not set" seems fixed.

**Comment by ahmetalpbalkan** [comment]
@sceee thanks for the input.  Yeah looks like existing setup or some problem in associating `.sh` to Git Bash application causes this issue.

**Comment by tianon** [comment]
:disappointed: 

Rewriting this `.sh` file in Go is definitely an option, but it adds an extra compilation step to the release and would still need to be able to find your Git Bash installation to fire up Bash when it finishes, so I'm not 100% convinced necessarily that this is a better option than something like #43 unless we have some pretty good logic for detecting a pre-installed Git Bash. :+1:

I suppose if it can't find Git Bash, it could print a large, hairy warning and then `execve` into `boot2docker ssh` directly and skip the middle man.

**Comment by SvenDowideit** [comment]
as per #97 I'm removing the `clear` in #104 - its not really needed.

the `PATH` issue is also noted in #103, we could add the dir that the script is in to the local `PATH` to help with that.

`.sh` association is really the hardest to solve. There _is_ a different approach someone could try though.

rather than associating the `start.sh` script with git's bash, we could add `start.sh` to the user's `.bashrc` with some kind of conditional logic, and then lay down a shortcut that triggered that condition.

Anyone want to play with it? :)

**Comment by anikitenko** [comment]
I experienced the same issues, except with `clear`. The problem with `.sh` was resolved by installing Git one more time and selecting option "Associate with .sh extension".
The problem with `HOME` was resolved by adding the following line at empty line 35:
`export HOME=$HOMEPATH`

**Comment by count023** [comment]
Hi there.

Experienced all the mentioned issued myself (This one is the best thread so far, to help out ;) )

But honestly ... Anybody working on this problems right now?

I know, it's not a this easy topic to cover all the different client conditions, but an installer which just do the half of the work not for just a few? Hmmm ... ;)

AND: If currently nobody get the time to fix, then pls provide a "WhatToDo" for any of the errors.Best  in the Readme or in the docs (KnownIssues.md for example) ... Thanks folks ... great work so far...

**Comment by count023** [comment]
PS.: 

    if [ "$HOME" == "" ]; then echo "homeless"; fi

;)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
