### ISSUE TITLE
Not installing docker.exe & boot2docker.exe to path results in failures in Boot2Docker Start

### ISSUE THREAD

**Issue by bbodenmiller** [boot2docker/windows-installer#103]
If you uncheck the option to install docker.exe & boot2docker.exe to your path the docker & boot2docker commands do not work in Boot2Docker Start. If they are required, why is unchecking them even an option?

**Comment by SvenDowideit** [comment]
mmmm, there was a reason, but its so far back in my dark history, i just don't remember.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
