### ISSUE TITLE
Issues with SSL cert

### ISSUE THREAD

**Issue by ndarilek** [boot2docker/windows-installer#105]
```
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH='C:\Users\nolan\.boot2docker\certs\boot2docker-vm'
export DOCKER_TLS_VERIFY=1
```

bash-3.1$ boot2docker up
Waiting for VM and Docker daemon to start...
............o
Started.
Writing C:\Users\nolan.boot2docker\certs\boot2docker-vm\ca.pem
Writing C:\Users\nolan.boot2docker\certs\boot2docker-vm\cert.pem
Writing C:\Users\nolan.boot2docker\certs\boot2docker-vm\key.pem
Your environment variables are already set correctly.

bash-3.1$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): windows/amd64
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/versi
on: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103

The ISO is at version 1.7.0 as well.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
