### ISSUE TITLE
ENH: On Windows, add VirtualBox and Git path in addition to Boot2Docker

### ISSUE THREAD

**Issue by jakirkham** [boot2docker/windows-installer#106]
At present, the installer for Windows add Boot2Docker to the user's path, which is good. However, it should also add VirtualBox and Git to the path at the same time.

**Comment by jack71** [comment]
:+1:

**Comment by roy128** [comment]
:+1:

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
