### ISSUE TITLE
Unable to install docker on windows

### ISSUE THREAD

**Issue by kirtangajjar** [boot2docker/windows-installer#107]
![untitled](https://cloud.githubusercontent.com/assets/8456197/8636554/8c3b34d2-2886-11e5-9214-717c9d4f7cbd.png)
When i try to run boot2docker start from desktop, it gives me the following error - start.sh: line 5: clear: command not found

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
