### ISSUE TITLE
Can't connect to Virtual Machine's server on Windows7 boot2docker 1.7.0

### ISSUE THREAD

**Issue by ghost** [boot2docker/windows-installer#109]
I can't make Docker run the Hello-world or any of server-connection things, as you can see it gives me the client version but at the time of giving me the server version it just can't connect...
![](http://i.stack.imgur.com/ahSWn.png)
I have boot2docker 1.7.0 and running on Windows 7.

![](http://i.imgur.com/NKCdOqZ.png)
As you can see here I dont get any error message at the start!

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
