### ISSUE TITLE
Boot2Docker Start shell script is not executed if .sh file extension is already associated with a different application than bash

### ISSUE THREAD

**Issue by matthias-m** [boot2docker/windows-installer#11]
If on Windows the .sh file extension is associated with e.g. a text editor before Boot2Docker is instaled on the system executing the start.sh script failes.

Workaround: Associate .sh with bash.exe

**Comment by enewton** [comment]
On Windows 7, I had the same problem. I tried deleting the old associations before re-installing and I tried to correct the association, but then I got path problems, as the script couldn't find the 'linux' EXEs.

I think it's now working (just started playing)
So I had to manually associate .sh with C:\Program Files (x86)\Git\bin\bash.exe
and had to add C:\Program Files (x86)\Git\bin to my path

Could the installer not overwrite the association?
Does the installer attempt to set the path?
Have I picked the correct bash.exe? as there was another one on my system?

**Comment by enewton** [comment]
Spoke too soon. Now I have:
error in run: Failed to start machine "boot2docker-vm" (run again with -v for details)
which I think I've seen elsewhere when trying to find a solution to my original problem

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
