### ISSUE TITLE
boot2docker fails without a C drive

### ISSUE THREAD

**Issue by DeezCashews** [boot2docker/windows-installer#110]
I have Windows 7 installed to a drive labeled `O:` (remnants of switching to an SSD drive a while back).  When trying to start boot2docker, it throws an error stating it can't find `C:\Users`.  Now I can't just rename my drive `C:` unfortunately (with all the references to `O:` in the registry, etc.).  I decided for a short term solution to set a USB drive to `C:` just to see what happens and am happy to say it worked perfectly.  Examining the drive, there is not a single thing written to it.  All of the boot2docker files are where they should be under `O:\Users\me\\.boot2docker`.  So obviously its using `%USERPROFILE%` or something similar at some point, but I'm not sure what in the beginning is hard coded to check C:\Users causing the failure.

**Comment by Soundvessel** [comment]
I would like to echo my concern that boot2docker requires the `C:\Users` path. Locking users to a particular drive or folder for file sharing creates horrible hard drive limitations.

For example Kalabox is a local development environment but [now suffers from an issue](https://github.com/kalabox/kalabox/issues/1266) that application code must exist in the `C:\Users` directory. Large applications would force developers to either make more space on their primary drive or go through cloning to a larger replacement.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
