### ISSUE TITLE
boot2docker on win7 64bit : Cannot start container <container ID>: [8] System error: no such file or directory

### ISSUE THREAD

**Issue by drasamsetti** [boot2docker/windows-installer#112]
After building the docker images successfully...
when docker run command initiated... getting same error for all containers.
It happens with all the docker images... :( 
Error response from daemon: Cannot start container <container ID>: [8] System error: no such file or directory

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
