### ISSUE TITLE
first start boot2docker in windows10 errors and exit

### ISSUE THREAD

**Issue by KeyHui** [boot2docker/windows-installer#113]
first start boot2docker in windows10 errors and exit

**Comment by andrewfaria** [comment]
Known issue with VirtualBox.

```
$ VBoxManage hostonlyif create
0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 70 of file VBoxManageHostonly.cpp
```

**Comment by KeyHui** [comment]
@andrewfaria thank you for your help, do you have fixed this bug? and can you use boot2docker in windows10?

**Comment by bparrish99** [comment]
I think it's a VirtualBox issue, so we have to wait until Oracle fixes it.  :(

https://www.virtualbox.org/ticket/14040

**Comment by andrewfaria** [comment]
@KeyHui found a workaround but haven't tested it yet: https://forums.virtualbox.org/viewtopic.php?f=6&t=67237#p326990

**Comment by andrewfaria** [comment]
A short-term working patch was released last night! Tested and it works.
https://www.virtualbox.org/ticket/14040#comment:36

**Comment by KeyHui** [comment]
@andrewfaria Can you show your step ? I also break when first click boot2docker, thank your

**Comment by andrewfaria** [comment]
@KeyHui 
1. download the executable at https://www.virtualbox.org/attachment/ticket/14040/VBox-Win10-fix-14040.exe
2. Right-click on the executable and select Run as Administrator
3. You may need to run
```sh
boot2docker delete
boot2docker init
eval "$(boot2docker shellinit)"
boot2docker up
```

**Comment by KeyHui** [comment]
@andrewfaria boot2docker will be exit after I choose the confirm that create host-only. Do you have this?

**Comment by andrewfaria** [comment]
@KeyHui is there an error message?

**Comment by KeyHui** [comment]
00:23:45.408 | --------         | Logging started
00:23:45.408 | VboxFix          | hAdvapi32 = 00007FFDBAB60000, pRegQueryValueExW = 00007FFDBAB76C70
00:23:45.408 | Main             | Executing subprocess "D:\softs\vbox\VBoxSVC.exe" /Helper VirtualBox\SVCHelper\{ba0a8678-349c-4cf8-abdc-5ea1f7350188}
00:23:45.480 | E:CreateProcess  | ID: 7096, 0x00007FF7542D0000 => \Device\HarddiskVolume2\softs\vbox\VBoxSVC.exe
00:23:45.480 | E:LoadDll        | 0x00007FFDBCD60000 => \Device\HarddiskVolume1\Windows\System32\ntdll.dll
00:23:45.481 | E:LoadDll        | 0x00007FFDBAE40000 => \Device\HarddiskVolume1\Windows\System32\kernel32.dll
00:23:45.481 | E:LoadDll        | 0x00007FFDBA250000 => \Device\HarddiskVolume1\Windows\System32\KernelBase.dll
00:23:45.482 | E:LoadDll        | 0x00007FFDB7DF0000 => \Device\HarddiskVolume1\Windows\System32\apphelp.dll
00:23:45.483 | E:LoadDll        | 0x00007FFDBAE30000 => \Device\HarddiskVolume1\Windows\System32\psapi.dll
00:23:45.483 | E:CreateThread   | ID: 1640
00:23:45.483 | E:LoadDll        | 0x00007FFDB97D0000 => \Device\HarddiskVolume1\Windows\System32\powrprof.dll
00:23:45.483 | E:LoadDll        | 0x00007FFDBA900000 => \Device\HarddiskVolume1\Windows\System32\msvcrt.dll
00:23:45.483 | E:LoadDll        | 0x00007FFDBA7D0000 => \Device\HarddiskVolume1\Windows\System32\rpcrt4.dll
00:23:45.484 | E:CreateThread   | ID: 5532
00:23:45.484 | E:CreateThread   | ID: 784
00:23:45.484 | E:LoadDll        | 0x00007FFDBAA10000 => \Device\HarddiskVolume1\Windows\System32\user32.dll
00:23:45.484 | E:LoadDll        | 0x0000000076930000 => \Device\HarddiskVolume2\softs\vbox\msvcr100.dll
00:23:45.484 | E:LoadDll        | 0x0000000076890000 => \Device\HarddiskVolume2\softs\vbox\msvcp100.dll
00:23:45.484 | E:LoadDll        | 0x00007FFDBCAE0000 => \Device\HarddiskVolume1\Windows\System32\gdi32.dll
00:23:45.484 | E:LoadDll        | 0x00007FFDB8F00000 => \Device\HarddiskVolume1\Windows\System32\dnsapi.dll
00:23:45.484 | E:LoadDll        | 0x00007FFD9FD90000 => \Device\HarddiskVolume2\softs\vbox\VBoxDDU.dll
00:23:45.484 | E:LoadDll        | 0x00007FFDBAB60000 => \Device\HarddiskVolume1\Windows\System32\advapi32.dll
00:23:45.484 | Breakpoint       | Added at 0x00007FFDBAB76C70 (orig. 0x48)
00:23:45.484 | E:LoadDll        | 0x00007FFDBA9A0000 => \Device\HarddiskVolume1\Windows\System32\ws2_32.dll
00:23:45.485 | E:LoadDll        | 0x00007FFD9DC70000 => \Device\HarddiskVolume1\Windows\System32\newdev.dll
00:23:45.485 | E:LoadDll        | 0x00007FFDBB160000 => \Device\HarddiskVolume1\Windows\System32\setupapi.dll
00:23:45.485 | E:LoadDll        | 0x00007FFDBA430000 => \Device\HarddiskVolume1\Windows\System32\sechost.dll
00:23:45.485 | E:LoadDll        | 0x00007FFDBCD50000 => \Device\HarddiskVolume1\Windows\System32\nsi.dll
00:23:45.485 | E:LoadDll        | 0x00007FFDB9BD0000 => \Device\HarddiskVolume1\Windows\System32\cfgmgr32.dll
00:23:45.485 | E:LoadDll        | 0x00007FFDBB5B0000 => \Device\HarddiskVolume1\Windows\System32\shell32.dll
00:23:45.485 | E:LoadDll        | 0x00007FFDBB330000 => \Device\HarddiskVolume1\Windows\System32\combase.dll
00:23:45.485 | E:LoadDll        | 0x00007FFD9C630000 => \Device\HarddiskVolume2\softs\vbox\VBoxRT.dll
00:23:45.485 | E:LoadDll        | 0x00007FFDB9C20000 => \Device\HarddiskVolume1\Windows\System32\windows.storage.dll
00:23:45.486 | E:LoadDll        | 0x00007FFDBA770000 => \Device\HarddiskVolume1\Windows\System32\shlwapi.dll
00:23:45.486 | E:LoadDll        | 0x00007FFDB9820000 => \Device\HarddiskVolume1\Windows\System32\kernel.appcore.dll
00:23:45.486 | E:LoadDll        | 0x00007FFDB8010000 => \Device\HarddiskVolume1\Windows\System32\uxtheme.dll
00:23:45.486 | E:LoadDll        | 0x00007FFDB9890000 => \Device\HarddiskVolume1\Windows\System32\SHCore.dll
00:23:45.486 | E:LoadDll        | 0x00007FFDB97B0000 => \Device\HarddiskVolume1\Windows\System32\profapi.dll
00:23:45.486 | E:LoadDll        | 0x00007FFDB42E0000 => \Device\HarddiskVolume1\Windows\System32\devrtl.dll
00:23:45.486 | E:LoadDll        | 0x00007FFDBB010000 => \Device\HarddiskVolume1\Windows\System32\ole32.dll
00:23:45.487 | E:LoadDll        | 0x00007FFDBAC10000 => \Device\HarddiskVolume1\Windows\System32\oleaut32.dll
00:23:45.487 | E:LoadDll        | 0x00007FFDB74C0000 => \Device\HarddiskVolume1\Windows\System32\IPHLPAPI.DLL
00:23:45.487 | E:LoadDll        | 0x00007FFDB7390000 => \Device\HarddiskVolume1\Windows\System32\winnsi.dll
00:23:45.489 | E:Exception      | 0x80000003 at 0x00007FFDBCE1E250 (first chance)
00:23:45.490 | E:LoadDll        | 0x00007FFDBA490000 => \Device\HarddiskVolume1\Windows\System32\imm32.dll
00:23:45.490 | E:LoadDll        | 0x00007FFDBACD0000 => \Device\HarddiskVolume1\Windows\System32\msctf.dll
00:23:45.491 | E:LoadDll        | 0x00007FFDB8AB0000 => \Device\HarddiskVolume1\Windows\System32\nvinitx.dll
00:23:45.491 | E:LoadDll        | 0x00007FFDB8B50000 => \Device\HarddiskVolume1\Windows\System32\version.dll
00:23:45.493 | E:LoadDll        | 0x000000000F000000 => \Device\HarddiskVolume1\Program Files\NVIDIA Corporation\coprocmanager\_etoured.dll
00:23:45.493 | E:LoadDll        | 0x00007FFDB6490000 => \Device\HarddiskVolume1\Program Files\NVIDIA Corporation\coprocmanager\nvd3d9wrapx.dll
00:23:45.494 | E:LoadDll        | 0x00007FFDB51E0000 => \Device\HarddiskVolume1\Program Files\NVIDIA Corporation\coprocmanager\nvdxgiwrapx.dll
00:23:45.497 | E:Exception      | 0x406D1388 at 0x00007FFDBA27A1C8 (first chance)
00:23:45.497 | E:LoadDll        | 0x00007FFDB95E0000 => \Device\HarddiskVolume1\Windows\System32\bcryptprimitives.dll
00:23:45.498 | E:LoadDll        | 0x00007FFDB80B0000 => \Device\HarddiskVolume1\Windows\System32\devobj.dll
00:23:45.499 | E:LoadDll        | 0x00007FFD9F130000 => \Device\HarddiskVolume1\Windows\System32\drvstore.dll
00:23:45.554 | E:LoadDll        | 0x00007FFDB9410000 => \Device\HarddiskVolume1\Windows\System32\SPInf.dll
00:23:46.103 | E:LoadDll        | 0x00007FFDB9830000 => \Device\HarddiskVolume1\Windows\System32\wintrust.dll
00:23:46.103 | E:LoadDll        | 0x00007FFDB9790000 => \Device\HarddiskVolume1\Windows\System32\msasn1.dll
00:23:46.104 | E:LoadDll        | 0x00007FFDB9950000 => \Device\HarddiskVolume1\Windows\System32\crypt32.dll
00:23:46.750 | E:ExitThread     | ID: 1640, Exit code: 0
00:23:46.750 | E:ExitThread     | ID: 784, Exit code: 0
00:23:46.750 | E:ExitThread     | ID: 5532, Exit code: 0
00:23:46.751 | E:ExitProcess    | Exit code: 0
00:23:46.751 | --------         | Logging stopped

by VBox-Win10-fix-14040.20150802-002345-7448.log

**Comment by KeyHui** [comment]
@andrewfaria  thank you for your help , I setup system again. I found the problem that new NVIDIA driver in windows 10

**Comment by yxlwfds** [comment]
win10 update  virtualbox to5.08 then delete virtual instance ,last run it

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
