### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by darenwhite** [boot2docker/windows-installer#114]
I have associated the .sh file to the installed sh.exe but whenever I run the Start a command window appears then disappears. If I run the sh.exe manually and then run each command separately it tells me the clear command cannot be found (sometimes the command window closes itself when this is run). Has anyone got any ideas this is running on Windows 7.
Thanks in advance

**Comment by darenwhite** [comment]
Just to add to this I have tried uninstalling and re-installing from scratch several times.

**Comment by sunshinemu** [comment]
I am having this issue as well on virtual box 4.3 and 5.0

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
