### ISSUE TITLE
Win 10: docker version - connection refused

### ISSUE THREAD

**Issue by vaskrist** [boot2docker/windows-installer#116]
##### After a few hickups I got boot2docker running fine on Windows 10
- installed latest VirtualBox 5.0.1 to fix the host adapter problem
- installed latest boot2docker 1.7.1 to skirt around VirtualBox 5 --synthcpu problem
- fixed IPv4 address problem when the start.sh script could get no IPv4 address to connect
  - removed all VirtualBox adapters from within VirtualBox (File > Options ... > Network > Host Only)
  - let the start.sh script generate a new VirtualBox adapter when creating the vm
  - got the IPv4 address from the newly created adapter
  - set fixed address to eth1 in vm (`ifconfig eth1 192.168.183.1 netmask 255.255.255.0`) 
- deleted certificates `rm /var/lib/boot2docker/tls/*.pem` and restarted the daemon `/etc/init.d/docker restart`
##### Now I can
- use docker from within the vm
- ping the vm IPv4 address 192.168.183.1
- call the remote interface over https from within the vm
  - `curl --insecure --cert /var/lib/boot2docker/tls/cert.pem --key /var/lib/boot2docker/tls/key.pem https://192.168.183.1:2376/v1.19/version`
##### But
- calling the remote interface over https from the git shell fails
  - `curl --insecure --cert ~/.boot2docker/certs/boot2docker-vm/cert.pem --key ~/.
    boot2docker/certs/boot2docker-vm/key.pem https://192.168.183.1:2376/v1.19/version`

```
curl: (7) Failed to connect to 192.168.183.1 port 2376: Connection refused
```
- `docker version` from git shell fails:

```
Vaskrist@VORTEX ~
$ docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): windows/amd64
An error occurred trying to connect: Get https://192.168.183.1:2376/v1.19/version: dial tcp 192.168.183.1:2376: ConnectEx tcp: No connection could be made because the
 target machine actively refused it.
```

**Comment by cgudrian** [comment]
I'm facing the same issue on Windows 7:

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://localhost:2375/v1.21/version: dial tcp 127.0.0.1:2375: ConnectEx tcp: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung
verweigerte.
```

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
