### ISSUE TITLE
boot2docker fails to start on Windows 2008 R2

### ISSUE THREAD

**Issue by barbarello** [boot2docker/windows-installer#117]
- Downloaded https://github.com/boot2docker/windows-installer/releases/tag/v1.7.1 and installed it on a Windows 2008 R2 Standard VM according to instructions at http://docs.docker.com/installation/windows/.
- Added "C:\Program File (x86)\Git\bin" to PATH.
- bootdocker init
- boot2docker up -v  

![image](https://cloud.githubusercontent.com/assets/5070341/9178280/5ed0ee70-3f64-11e5-90ba-50ef3badbced.png)

there is no other processes on port 2022 , yet  I still get "Error requesting socket: exit status 255"

also tried boot2docker ssh -
![image](https://cloud.githubusercontent.com/assets/5070341/9178404/1ad26716-3f65-11e5-82a5-b8844c91d67b.png)

Any help appreciated !!!

**Comment by barbarello** [comment]
also tried boot2docker ssh -v

![image](https://cloud.githubusercontent.com/assets/5070341/9178366/e6be41e8-3f64-11e5-9ba2-a124367b1c72.png)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
