### ISSUE TITLE
Bad port '0' on boot2docker ssh comand on windows 8

### ISSUE THREAD

**Issue by GosthMan** [boot2docker/windows-installer#118]
Hello,

I have installed boot2docker on windows 8 and when i try ssh from the git bash i'm unable to connect.
I would like to know what setting shall i set on profile in order to be able to use boot2docker.exe command
The boot2docker VM works and docker too because i am able to connect using putty
$ boot2docker.exe ssh
Bad port '0'
error in run: exit status 255
$ boot2docker.exe config
# boot2docker profile filename: C:\Users\ioan.pop.boot2docker\profile

Init = false
Verbose = false
Driver = "virtualbox"
Clobber = false
ForceUpgradeDownload = false
SSH = "ssh"
SSHGen = "ssh-keygen"
SSHKey = "C:\Users\ioan.pop\.ssh\id_boot2docker"
VM = "boot2docker-vm"
Dir = "C:\Users\ioan.pop\.boot2docker"
ISOURL = "https://api.github.com/repos/boot2docker/boot2docker/releases"
ISO = "C:\Users\ioan.pop\.boot2docker\boot2docker.iso"
DiskSize = 40000
Memory = 2048
CPUs = 4
SSHPort = 2022
DockerPort = 2376
HostIP = "192.168.100.2"
DHCPIP = "192.168.100.1"
NetMask = [255, 255, 255, 0]
LowerIP = "192.168.100.2"
UpperIP = "192.168.100.254"
DHCPEnabled = false
Serial = false
SerialFile = "\\.\pipe\boot2docker-vm"
Waittime = 300
Retries = 75
$ boot2docker.exe info
{
        "Name": "boot2docker-vm",
        "UUID": "a627244e-4ace-43c4-a4eb-a6f54182b618",
        "Iso": "C:\Users\ioan.pop\.boot2docker\boot2docker.iso",
        "State": "running",
        "CPUs": 4,
        "Memory": 2048,
        "VRAM": 8,
        "CfgFile": "C:\\Users\\ioan.pop\\Desktop\\Ioan\\Virtual Machin
es\\boot2docker-vm\\boot2docker-vm.vbox",
        "BaseFolder": "C:\Users\ioan.pop\Desktop\Ioan\Virtual Machines\boo
t2docker-vm",
        "OSType": "",
        "Flag": 0,
        "BootOrder": null,
        "DockerPort": 0,
        "SSHPort": 0,
        "SerialFile": "\\.\pipe\boot2docker-vm"
}

Docker command works 
$ docker info
Containers: 4
Images: 66
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.7-boot2docker
Operating System: Boot2Docker 1.7.1 (TCL 6.3); master : c202798 - Wed Jul 15 00:
16:02 UTC 2015
CPUs: 4
Total Memory: 1.955 GiB
Name: boot2docker
ID: DAS4:V3HW:JAOX:4VW3:VBRL:BXZB:ETMJ:34E7:JILH:IGWR:VDZ6:Y7T7
Debug mode (server): true
File Descriptors: 27
Goroutines: 43
System Time: 2015-08-10T22:56:03.880915914Z
EventsListeners: 1
Init SHA1:
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

$ docker.exe ps
CONTAINER ID        IMAGE                      COMMAND                CREATED
          STATUS              PORTS
                            NAMES
3eb26a706041        shipyard/shipyard:latest   "/controller"          3 days ago
          Up 10 minutes       0.0.0.0:8080->8080/tcp
                            shipyard
bd9c83790398        shipyard/rethinkdb         "/usr/bin/rethinkdb    3 days ago
          Up 10 minutes       0.0.0.0:32770->8080/tcp, 0.0.0.0:32769->28015/tcp,
 0.0.0.0:32768->29015/tcp   shipyard-rethinkdb
6e226d6ea753        shipyard/rethinkdb         "/bin/bash -l"         3 days ago
          Up 10 minutes       8080/tcp, 28015/tcp, 29015/tcp
                            shipyard-rethinkdb-data

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
