### ISSUE TITLE
Path to a certificate and key files must be provided

### ISSUE THREAD

**Issue by redtil** [boot2docker/windows-installer#119]
For the past few days I have been trying to trace the source of the error shown in the blockquote in trying to deploy an app to google app engine on a windows machine using the command:

> gcloud preview app deploy app.yaml
> Beginning deployment... Verifying that Managed VMs are enabled and ready.

Traceback (most recent call last): ...

File "C:\Program Files\Google\Cloud SDK\google-cloud-sdk\bin.../lib\docker\docker\tls.py", line 46, in init

'Path to a certificate and key files must be provided'

TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations.
Does anyone have any idea on how to solve this issue?

FYI: I have already set the environment variables DOCKER_CERT_PATH, DOCKER_TLS_VERIFY and DOCKER_HOST as set by Docker.

**Comment by LusciousPear** [comment]
+1

**Comment by toddpi314** [comment]
+1. To the credit of the docker team, this might be a gcloud SDK issue.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
