### ISSUE TITLE
do we plan for 1.8.1 release ?

### ISSUE THREAD

**Issue by larrycai** [boot2docker/windows-installer#120]
There are some bugs in 1.8.0 release, will be nice if you plan to have 1.8.1 release. 

Though it is deprecated, will be appreciated to keep this track for a while

thx

**Comment by chaokw** [comment]
Which version is most stable just now? Thx

**Comment by yosifkit** [comment]
As far as docker releases, the current is `1.11.2`.

> This project (the boot2docker Windows Installer) is officially deprecated in favor of the new Docker Toolbox.
> 
> https://github.com/boot2docker/windows-installer#deprecated
