### ISSUE TITLE
ftp

### ISSUE THREAD

**Issue by spiritelf** [boot2docker/windows-installer#121]
错误: 无法连接到服务器
状态: 已从服务器断开
状态: 正在连接 192.168.59.103...
响应: fzSftp started, protocol_version=2
命令: open "root@192.168.59.103" 22
命令: Pass: ****
can help?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
