### ISSUE TITLE
boot2docker in windows 10 hyperv won't boot / cannot get ip address

### ISSUE THREAD

**Issue by joshuahayes** [boot2docker/windows-installer#122]
I have tried the boot2docker iso from here (v17.03.0-ce) as well as the boot2docker.iso from the latest toolbox install (uninstalled virtualbox). Whether creating a new vm with the boot2docker iso manually via hyperv manager or via docker-machine command line, both result in the vm not booting due to boot2docker not reporting an ip address.

**Steps to reproduce via hyperv manager:**

- Setup external virtual switch
![image](https://cloud.githubusercontent.com/assets/1720052/23946249/cefda3a2-09cd-11e7-8fe6-baa230827b12.png)
- Create new vm from boot2docker.iso with the previously configured external switch

The boot2docker vm gets stuck with the following message _**'Waiting as requested... 10'**_
![image](https://cloud.githubusercontent.com/assets/1720052/23945991/c2518282-09cc-11e7-9d02-f2b277bd0792.png)

Further investigation in docker-machine debug shows that the VM is not reporting an ip address and perpetually hangs.

**Steps to re-produce via docker-machine:**

- Open powershell in Admin mode
-Run _docker-machine --debug create --driver hyperv --hyperv-virtual-switch 'External' boot2docker_

![image](https://cloud.githubusercontent.com/assets/1720052/23946291/fca2fd5c-09cd-11e7-94a8-5b5ad225186d.png)

![image](https://cloud.githubusercontent.com/assets/1720052/23946318/0f42166e-09ce-11e7-9bdc-f9f7fa87e782.png)

**Comment by vyfster** [comment]
@joshuahayes did you ever get this to work?  I am experiencing the same problem.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
