### ISSUE TITLE
Start fails with VT-x not supported error when Hyper-V is enabled

### ISSUE THREAD

**Issue by schlenk** [boot2docker/windows-installer#13]
This is more a VirtualBox issue than it is a boot2docker problem, but might be helpful to add it to the FAQ or documentation.

In order to run boot2docker on Windows you need to have a cpu with VT-x and must not have the hyper-v feature installed, otherwise virtualbox refuses to start the VM with this message:

```
2014/06/11 22:19:04 Failed to start machine "boot2docker-vm" (run again with -v
for details)
```

Maybe the installer could check for an installed Hyper-V and warn about it, didn't see an obvious way to check for installed windows features in InnoSetup though.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
