### ISSUE TITLE
Windows 32-bit installer

### ISSUE THREAD

**Issue by TNick** [boot2docker/windows-installer#14]
So, I'm the only one left with a Windows 7 32-bit, huh?
:)

**Comment by memark** [comment]
@ahmetalpbalkan, instead of uninstalling Hyper-V, you can just disable it temporarily. Here's a way:
http://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx

**Comment by ahmetalpbalkan** [comment]
@memark ah nice to know thanks

**Comment by samayo** [comment]
@SvenDowideit  It has been more than a year since this issue opened. Do you have any news? I'm also stuck with windows 7 32 bit. I had installed windows 10 but docker does not run on that also.

**Comment by StefanScherer** [comment]
A 32bit `boot2docker.iso` would help build some integration tests eg. for `docker-machine` to run on Travis, Circle, AppVeyor. They all do not support nested hypervisor, but should be able to spin up 32bit VM's.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
