### ISSUE TITLE
add the boot2docker install path to the user's / system PATH?

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/windows-installer#22]
Adding `c:\Pro...\Git\bin\` path to ssh too would make `boot2docker.exe ip` and `boto2docker.exe ssh` work in cmd.exe

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
