### ISSUE TITLE
AVG gives "Trojan Horse FakeAlert.RT" warning at bootdocker.exe

### ISSUE THREAD

**Issue by husayt** [boot2docker/windows-installer#27]
i installed Docker for windows from 
https://github.com/boot2docker/windows-installer/releases/download/v1.1.0/docker-install.exe

and i  get "Trojan Horse FakeAlert.RT" warning from AVG Antivirus

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
