### ISSUE TITLE
document to add "boot2docker download behind firewall"

### ISSUE THREAD

**Issue by larrycai** [boot2docker/windows-installer#29]
In order to upgrade from the existing boot2docker, I try to download iso directly as suggested after stop boot2docker, and noticed we need proxy.

Better to add extra documentation in http://docs.docker.com/installation/windows/#upgrading for this 
- `export http_proxy/https_proxy`
  or
- download the iso from https://github.com/boot2docker/boot2docker/releases directly and save into ~/.boot2docker

Or is it possible to reuse the system proxy ?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
