### ISSUE TITLE
uninstall/install new boot2docker will not install new iso

### ISSUE THREAD

**Issue by larrycai** [boot2docker/windows-installer#30]
Even uninstall the boot2docker old version and install the new version, the version is not changed.

It is because that uninstall command will not remove `~/.boot2docker` directory which contain `boot2docker.iso`

Therefore during the new installation phase, `start.sh` detects the `~/.boot2docker/boot2docker.iso` exists, then the copy/download will not happen.

Suggest to remove boot2docker VM in virtualbox and `~/.boot2docker` directory completely, or at least give remind.

Or update the script to add a check if there are new iso, then replace it. (like upgrade)

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
