### ISSUE TITLE
Windows 7 64 bit: first attempt at install did not work - how do I cleanly uninstall?

### ISSUE THREAD

**Issue by chewmanfoo** [boot2docker/windows-installer#33]
I already have VirtualBox on my laptop for vagrant - it works fine.

I go to install boot2docker - it failed, see below:

  Welcome to Git (version 1.9.0-preview20140217)

  Run 'git help git' to display the help index.
  Run 'git help <command>' to display help for specific commands.
  copying initial boot2docker.iso (run 'boot2docker.exe download' to update
  initializing...
  Generating public/private rsa key pair.
  Your identification has been saved in c:\Users\sg0218049.ssh\id_boot2docker.
  Your public key has been saved in c:\Users\sg0218049.ssh\id_boot2docker.pub.
  The key fingerprint is:
  9b:2c:1d:4a:47:66:4c:8a:b6:0b:43:7b:55:d3:2c:af SG0218049@H8460305330995
  2014/07/22 11:02:52 Creating VM boot2docker-vm...
  2014/07/22 11:02:52 Apply interim patch to VM boot2docker-vm (https://www.virtua
  lbox.org/ticket/12748)
  2014/07/22 11:02:52 Failed to modify VM "boot2docker-vm": exit status 1
  starting...
  2014/07/22 11:02:53 Waiting for VM to be started...
  .............................
  2014/07/22 11:03:52 Started.
  2014/07/22 11:03:52   Trying to get IP one more time
  2014/07/22 11:03:52 exit status 255  
  2014/07/22 11:03:52 Docker client does not run on Windows for now. Please use
  2014/07/22 11:03:52     "c:\Program Files\Boot2Docker for Windows\boot2docker.ex
  e" ssh
  2014/07/22 11:03:52 to SSH into the VM instead.
  connecting...
  Bad port '0'
  2014/07/22 11:03:53 exit status 255

I then tried 'Uninstall Boot2Docker for Windows" and I get the message: "Some elements could not be removed.  These can be removed manually"  Which elements?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
