### ISSUE TITLE
exec: "ssh": executable file not found in %PATH%

### ISSUE THREAD

**Issue by nbu65** [boot2docker/windows-installer#37]
I've used installer v1.1.2
I get:

2014/08/09 16:21:41 Waiting for VM to be started...
.......2014/08/09 16:22:03 exec: "ssh": executable file not found in %PATH%

2014/08/09 16:22:03 Started.
2014/08/09 16:22:04   Trying to get IP one more time
2014/08/09 16:22:04 exec: "ssh": executable file not found in %PATH%
2014/08/09 16:22:04 Docker client does not run on Windows for now. Please use
2014/08/09 16:22:04     "e:\Programme\Boot2Docker for Windows\boot2docker.exe" ssh
2014/08/09 16:22:04 to SSH into the VM instead.
connecting...
2014/08/09 16:22:04 exec: "ssh": executable file not found in %PATH%

as in #19 
I think the problem ist the installation path. I installed boot2docker in
 E:\Programme\Boot2Docker for Windows

I've added
B2DPATH=${B2DPATH//E:\//\/e/}
in start.sh then it works.

**Comment by jfellien** [comment]
Hi,

I get the same message. But I've installed boot2docker on C:. The additional line in start.sh does not solve this issue. Any suggestion, what can I do?

**Comment by kklepper** [comment]
Add your **git\bin** directory to your path. As a permanent solution, change the path of your machine by adding this directory to the path string (if you don't know how to do this, there should be plenty of instructions in your language version online, so just google it). 

In your current session, do something like

    Your_path_to\Boot2Docker>path=%PATH%;your_path_to\Git\bin

Make sure you get what you want:

    Your_path_to\Boot2Docker>path

Next call

    Your_path_to\Boot2Docker>boot2docker.exe ssh

and you're set. You should see the familiar docker interface.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
