### ISSUE TITLE
boot2docker-vm is not working on Windows 7 64 bit machine 

### ISSUE THREAD

**Issue by nashid** [boot2docker/windows-installer#38]
I just tried the Docker v1.1.2

https://github.com/boot2docker/windows-installer/releases

However installation failed with:

2014/08/12 16:15:44 Failed to start machine "boot2docker-vm" (run again with -v
for details)
connecting...
2014/08/12 16:15:44 VM "boot2docker-vm" is not running.

Also tried "boot2docker init" followed by "boot2docker up". Same issue happeded:

c:\docker\boot2docker>boot2docker up
2014/08/12 16:25:14 Failed to start machine "boot2docker-vm" (run again with -v
for details)

Cannot find boot2docker-vm either.

**Comment by zongwan** [comment]
@SvenDowideit 
@nashid 
@diddou 

Enable cpu VTx may fix it.
[image_url](http://d-prototype.com/wp-content/uploads/2014/12/BIOS_VT-x_Support.png)

sorry , can not insert image directly.

solution from here:
Docker error：error in run: Failed to start machine “boot2docker-vm” - Adamhuan's Data Center - 【逻辑驱动数据】
http://d-prototype.com/archives/2073

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
