### ISSUE TITLE
copy files from local machine to boot2docker

### ISSUE THREAD

**Issue by priyanka5** [boot2docker/windows-installer#44]
Hi,

I am not able to copy any file from my machine to boot2docker running on windows machine , how to do this? I am facing difficulty to deploy my war in docker wildfly container due to this.

Thanks,
Priya

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
