### ISSUE TITLE
[UX] add the same info links and hints to the 'finished' installing page as in OSX-installer

### ISSUE THREAD

**Issue by SvenDowideit** [boot2docker/windows-installer#46]
<p>
        <ul>
        <li><b>Quick-Start: </b>Run Boot2Docker (located in Applications), which will open a terminal window. Then, start a test container with:<br /><code>docker run hello-world</code></li>
        </ul>
        <ul>
        <li>To save and share container images, automate workflows, and more sign-up for a free <a href="http://hub.docker.com/?utm_source=b2d&utm_medium=installer&utm_term=summary&utm_content=osx&utm_campaign=product">Docker Hub account</a>.</li>
        </ul>
        <ul>
    <li>You can upgrade your existing Boot2Docker VM without data loss by running: <br /><code>boot2docker upgrade</code></li>
        </ul>
        <ul>
        <li> The <code>docker</code> and <code>boot2docker</code> binaries are in <code>/usr/local/bin</code> which you can access from your terminal. </br>
         For further information, please see the <a href="http://docs.docker.com/installation/mac">Docker OS X installation documentation</a>.</li>
        </ul>
    </p>

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
