### ISSUE TITLE
VirtualBox selected to install but did not install

### ISSUE THREAD

**Issue by rshoda** [boot2docker/windows-installer#55]
On a Win7 machine, ran the v1.2.0 install with VirtualBox selected. 

After installation, when I ran Boot2Docker start, an error specified it could not find the VirtuallBox executable (displaying the path to the executable). When i checked for that directory, it had not been created.  

The VirtualBox 4.3.12 .msi file was in the Boot2Docker for Windows directory.

I had also previously downloaded the current VirtualBox 4.3.16 .msi file, which I installed instead of 4.3.12, and Boot2Docker ran with no further problems.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
