### ISSUE TITLE
Hyper-V support

### ISSUE THREAD

**Issue by alexsandro-xpt** [boot2docker/windows-installer#57]
There a chance get a hyper-v support in soon?

**Comment by sschuberth** [comment]
There also are several [issues in the boot2docker project](https://github.com/boot2docker/boot2docker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+hyper-v+) itself to track Hyper-V support.

Once the ISO would be working with Hyper-V, adding Hyper-V provider support to the [boot2docker-vagrant-box](https://github.com/mitchellh/boot2docker-vagrant-box/issues/36) would also nicely address this issue.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
