### ISSUE TITLE
Cannot launch docker on Windows 7

### ISSUE THREAD

**Issue by ebeyrent** [boot2docker/windows-installer#60]
I followed the installation instructions at https://docs.docker.com/installation/#installation and installed Docker via docker-install.exe.  When I launch docker, I get this:

initializing...
error in run: Failed to initialize machine "boot2docker-vm": exec: "C:\Program
Files\Oracle\VirtualBox\VBoxManage.exe": file does not exist
starting...
error in run: Failed to get machine "boot2docker-vm": exec: "C:\Program Files\
Oracle\VirtualBox\VBoxManage.exe": file does not exist
connecting...
error in run: Failed to get machine "boot2docker-vm": exec: "C:\Program Files\
Oracle\VirtualBox\VBoxManage.exe": file does not exist

[Hit a key to exit]

**Comment by luneslunes** [comment]
Deleting the folder `C:\Users\${username}\VirtualBox VMs\boot2docker-vm` worked for me, too.

**Comment by sunnymehta1987** [comment]
Hi all..i installed docker on windows,but when i m clicking Boot2Docker .its opening in notepad instead of running.please help me regarding this

**Comment by surfergirrl** [comment]
I used 'boot2docker ssh' in win7. think that was from a dos command window...

**Comment by webteckie** [comment]
I just installed Docker in my Windows 7 PC and same problem:

```
initializing...
error in run: Failed to initialize machine "boot2docker-vm": exec: "C:\\Program Files\\Oracle\\VirtualBox\\VBoxManage.exe": file does not exist

C:\Program Files\Boot2Docker for Windows>
```
I do not have that folder mentioned above; do not have Virtual Box installed.  The installation seems to have completed successfully and, in fact, it did prompt me for permissions to installed Oracle components, which I OK.

**Comment by webteckie** [comment]
https://forums.virtualbox.org/viewtopic.php?f=6&t=61785 solved my problem!

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
