### ISSUE TITLE
Installation of 1.3.0, it still reports versions as 1.2.0

### ISSUE THREAD

**Issue by CrawfordGriffith** [boot2docker/windows-installer#61]
Hi,

Installing 1.3.0 , it reports everything still at 1.2..0 level:

```
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
         \    \        __/
          \____\______/
```

---

| |__   ___   ___ | |_|___ \ **| | ___   ___| | ___** _ __
| '_ \ / _ \ / _ | **| __) / _` |/ _ \ / __| |/ / _ \ '**|
| |_) | (_) | (_) | |_ / **/ (_| | (_) | (**|   <  **/ |
|_.**/ _**/ _**/ __|_______,_|_**/ _**|_|\____|_|
boot2docker: 1.2.0
             3.16.1-config-file : e75396e - Fri Aug 22 06:45:30 UTC 2014
docker@boot2docker:~$ docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
docker@boot2docker:~$

I did an install of 1.3.0 over 1.2.0 with this result, then completely uninstalled Boot2Docker and did a clean installation, and the same result

Ideas?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
