### ISSUE TITLE
Fail to boot docker on windows 8 with error  "Shared folder named 'c/Users' already exists"

### ISSUE THREAD

**Issue by WongTai** [boot2docker/windows-installer#64]
2014/10/19 11:55:28 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
2014/10/19 11:55:29 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountPre
fix /
2014/10/19 11:55:29 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountDir
 /
2014/10/19 11:55:29 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe sharedfolder add boot2docker-vm --name c/Users --hostpath C:\Users --automou
nt
VBoxManage.exe: error: Shared folder named 'c/Users' already exists
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostpath).raw(), fWritable, fAutoMount)" at line 1009 of file VBoxManageMisc.cpp
2014/10/19 11:55:29 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe setextradata boot2docker-vm VBoxInternal2/SharedFoldersEnableSymlinksCreate/
c/Users 1
2014/10/19 11:55:29 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm boot2docker-vm --type headless
VBoxManage.exe: error: VT-x is disabled in the BIOS. (VERR_VMX_MSR_VMXON_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component Console, interface IConsole
2014/10/19 11:55:32 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo boot2docker-vm --machinereadable
error in run: Failed to start machine "boot2docker-vm" (run again with -v for details)

**Comment by frosforever** [comment]
+1 Windows 7 64 bit. Tried with VirtualBox 4.3.16, 4.3.18, & 4.3.20 with Boot2Docker 1.4.1

**Comment by Wangyunxing** [comment]
Please refer to http://stackoverflow.com/questions/27544622/boot2docker-start-up-fails

boot2docker delete; boot2docker download; boot2docker init; fixed this issue for me on a Mac. –  Usman Ismail Dec 18 '14 at 15:04

**Comment by damnhandy** [comment]
@Wangyunxing this doesn't fix the issue on Windows. It is most definitely an issue with VirtualBox as this issue was not present for me with VirtualBox 4.3.16. It affected both 4.3.18 and 4.3.20. 

@tianon @SvenDowideit This issue seems to be resolved with VirtualBox 4.3.22 and 4.3.26. I updated over the bundled 4.3.20 and things have been working ever since. I have tested it with both versions and have not had any issues since upgrading. I am now successfully running Boot2Docker 1.5.0 under VirtualBox 4.3.26 on a daily basis now. I'm curious if others can confirm this?

**Comment by damnhandy** [comment]
One more thing, you DO have to delete and rebuild the image when you install VBox 4.3.22 or better. Basically, if it you already created the boot2docker VM with 4.3.18 or 4.3.20, it will remain broken. My steps to fix was as follows:

* Delete the boot2docker VM
* Install VirtualBox 4.3.26
* Run Boot2Docker Start from the Start Menu. For some reason, `boot2docker init` didn't work initially

Once I did those steps, I was back in business. Oddly, once I had everything working again, `boot2docker init` was working again.

**Comment by DipendraG** [comment]
Basic thing to check is that you have Enabled the virtualization and VT-x option in the boot (windows 8)

**Comment by linouxis9** [comment]
The problem can also happened if you have Hyper-V activated.

**Comment by PLEEROCK** [comment]
I have this issue and my virtual box is 4.3.28

**Comment by ssmith15** [comment]
4.3.30 also not working. I'm going to try installing a previous version of VBox to see if that is the issue

**Comment by CoreMark** [comment]
Refer to: http://docs.docker.com/windows/step_one/
> Make sure your Windows system supports Hardware Virtualization Technology and that virtualization is enabled.

After setup this, the issue gone. My OS is Windows 7 and my virtual box is 4.3.28

**Comment by ssmith15** [comment]
I understand this now and it makes sense. But is there a way to circumvent this if we are running a windows virtual server? I've asked this question in multiple threads but, obviously you can't enable virtualization on a virtual server so I'm wondering what my alternatives are here.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
