### ISSUE TITLE
VBoxManage.exe: error: Unable to load R3 module

### ISSUE THREAD

**Issue by singleton7** [boot2docker/windows-installer#67]
Hello everyone.
I have get an error when I start docker,and I have no idea to resolve it.Please help me to find the reason,I'll thank you so much.The details error information is:
Boot2Docker-cli version: v1.3.0
Git commit: deafc19
2014/10/27 09:50:04 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 showvminfo boot2docker-vm --machinereadable
2014/10/27 09:50:05 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountPrefix
 /
2014/10/27 09:50:05 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 guestproperty set boot2docker-vm /VirtualBox/GuestAdd/SharedFolders/MountDir /
2014/10/27 09:50:05 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 sharedfolder add boot2docker-vm --name c/Users --hostpath C:\Users --automount
VBoxManage.exe: error: Shared folder named 'c/Users' already exists
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), componen
t SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostp
ath).raw(), fWritable, fAutoMount)" at line 1009 of file VBoxManageMisc.cpp
2014/10/27 09:50:05 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 setextradata boot2docker-vm VBoxInternal2/SharedFoldersEnableSymlinksCreate/c/U
sers 1
2014/10/27 09:50:05 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 startvm boot2docker-vm --type headless
Waiting for VM "boot2docker-vm" to power on...
VBoxManage.exe: error: Unable to load R3 module C:\Program Files\Oracle\VirtualB
ox/VBoxDD.DLL (VBoxDD): GetLastError=1790 (VERR_UNRESOLVED_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component Console, int
erface IConsole
2014/10/27 09:50:07 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 showvminfo boot2docker-vm --machinereadable
error in run: Failed to start machine "boot2docker-vm" (run again with -v for de
tails)

**Comment by Vitalicus** [comment]
Uninstall

**Comment by smoketh** [comment]
How about NO? I am sorry, how the hell does my uxtheme.dll has to do with anything? yes i have it patched and yes i use custom theme for my needs. Why should it matter at all?

**Comment by AW-UC** [comment]
@smoketh Yes, it sucks. But you should complain at https://www.virtualbox.org/ticket/13187, because this is a VitualBox issue. The only thing Boot2Docker could do is reverting to VirtualBox 4.3.12.

**Comment by Hackhong** [comment]
Thanks！It works after after Reverting to VirtualBox 4.3.12！

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
