### ISSUE TITLE
How to install without admin rights

### ISSUE THREAD

**Issue by pcavatore** [boot2docker/windows-installer#68]
How can I install the boot2docker windows installer without admin rights?

**Comment by davesomebody** [comment]
How about not needing admin rights once it is installed?  When I init the docker VM it asks for admin credentials twice.
My work laptop is locked down such that I don't have admin credentials.

**Comment by rtrauntvein** [comment]
Looks like the same as #78

**Comment by SvenDowideit** [comment]
agreed - #78 it is (slightly more info there)

I'm not at all sure there is a way to create a virtual machine without admin rights somewhere along the line, but i also don't recal if vmware made me do it.
