### ISSUE TITLE
b2d issues trying to run on windows 7 ultimate 64bit

### ISSUE THREAD

**Issue by epeleg** [boot2docker/windows-installer#73]
during installation it did not opt to install virtual box because it was already installed.
After installation completed the created boot2docker-vm refused to run

its settings said that the allocated 8Mb of video memory is not enough so I increased to 14M.

still did not run.

only upgrading virtual box to version 4.3.20 finally allowed the VM to run.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
