### ISSUE TITLE
b2d shellinit

### ISSUE THREAD

**Issue by markl17** [boot2docker/windows-installer#74]
instead of expecting some one to run it in bash why not test if windows then use set for those variables instead of export. Because set is a windows command unless you include some sort of export which actually does some sort of 'set' which i think is a waist of time

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
