### ISSUE TITLE
Folders in boot2docker

### ISSUE THREAD

**Issue by AnkitaBarbi** [boot2docker/windows-installer#77]
I am working in boot2docker and I have created some folders and files in it but whenever I switch off my system and switch it on again  , all the folders and files created in boot2docker are deleted . Can anyone say why is it so and hw to get them back?

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
