### ISSUE TITLE
How to init without windows admin?

### ISSUE THREAD

**Issue by davesomebody** [boot2docker/windows-installer#78]
I have no admin privs on the box I run boot2docker on and when I run init it tries to elevate to admin.

Finding someone with admin creds every time somebody needs to run init is not a workable solution.

When I got somebody to enter admin for me I learned that VirtualBox actually asks to elevate to admin twice during the boot2docker init process.

What exactly is it doing to VirtualBox that requires admin?  Is there some way to workaround this?

Thanks

**Comment by samling** [comment]
+1

**Comment by jeffreyroberts** [comment]
+1

**Comment by SvenDowideit** [comment]
I'm not at all sure there is a way to create a virtual machine without admin rights somewhere along the line, but i also don't recal if vmware made me do it.

**Comment by davesomebody** [comment]
The vagrant docker provider does not require any sort of escalation in windows to stand up a fresh VM, install an OS, provision docker and stand up some containers.  Of course I would rather use boot2docker.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
