### ISSUE TITLE
Installing boot2docker just wiped out Dropbox and Oracle Virtualbox!

### ISSUE THREAD

**Issue by joetidee** [boot2docker/windows-installer#79]
I just installed Boot2docker as per the Docker site and now my Dropbox installation and Oracle Virtualbox installations have disappeared from my system - the what the hell!!

**Comment by SvenDowideit** [comment]
no idea! thats never happened to me :( - especially as the installer _installs_ vbox.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
