### ISSUE TITLE
Error requesting socket on Windows 7

### ISSUE THREAD

**Issue by vce-xx** [boot2docker/windows-installer#81]
Hello
I am getting an error starting boot2docker on Windows 7 :

o2015/03/18 15:39:33 executing: C:\Program Files (x86)\Git\bin\ssh.exe ssh -o IdentitiesOnly=yes -o StrictHostKeyCheckin
g=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p 2022 -i c:\users\vce\.ssh\id_boot2docker docker@localhost grep
 tcp:// /proc/$(cat /var/run/docker.pid)/cmdline
Error requesting socket: exit status 255

The boot2docker VM is started in VirtualBox.

The boot2docker ip command returns :

Failed to get VM Host only IP address.
        Was the VM initialized using boot2docker?

The 2022 port is not open on localhost.

This is with boot2docker 1.5.0 and VirtualBox 4.3.24 r98716

Can you help me troubleshoot this ?

**Comment by SvenDowideit** [comment]
sometimes, creating the vm doesn't initilise everything correctly, and doing a `boot2docker delete` and `boot2docker init` fixes it.

to trouble shoot, I use the vbox GUI to look at the VM's network settings - the first adaptor should be set to NAT, and when you click the port forwarding (advanced?) button, there should a port forward from your localhost (2022? (i thought it was defaulted to 2222) to the vm's port 22)

**Comment by vce-xx** [comment]
Doing a boot2docker delete and boot2docker init did not fix it.

Upgrading to VirtualBox 4.3.26 r98988 did not help either : the boot2docker vm is not visible anymore in the GUI.

The boot2docker vm was visible with VB 4.3.24 r98716 and I was able to check that the port forwarding was correctly set. (However, port 2022 was not open on localhost. Reason why I updated my VirtualBox.)

boot2docker does not get the vm's ip address.

**Comment by vce-xx** [comment]
After removing boot2docker files and reinstalling, the issue was solved for me.
Not sure what the exact reason was, but it might be that the boot2docker-vm did not shutdown cleanly at some point and then remained in a bad state.
I thought I should let you know.
I am closing the issue now.
Keep up the good work guys !
