### ISSUE TITLE
Does not start when Windows RDS user profile disks is enabled

### ISSUE THREAD

**Issue by bsfmig-a** [boot2docker/windows-installer#84]
Windows Remote Desktop Services has a feature called "user profile disks" that puts user profiles into a VHDX file.
For example, when a user "user1" logs in, Windows creates or mounts a user profile virtual disk like "d:\userprofiles\UVHD-S-1-5-21-1941567458-2434135630-3624277251-1005.vhdx" and creates a symlink from "C:\Users\user1" to that VHDX file.
When the feature is enabled, Docker for Windows will not run, which complains "error in run: config error: failed to get boot2docker directory: readlink c:/Users/user1: The system cannot find the file specified."

**Comment by avlasov** [comment]
I'm running into the same issue, but I suspect my problem is that my Windows Users directory is a soft link to a directory on a different volume. Is there any workaround? Is there way to configure docker installer so that the .bootdocker dir is installed in a different location, not in $HOME? Or to change config files to move it there manually?

**Comment by rastaman** [comment]
Hi, i had the same problem with my homedir beeing a soft-link to another place, and as a workaround, i  had declare the USERPROFILE environment variable to the real path of my home dir in the startup script of boot2docker ( C:\Program Files\Boot2Docker for Windows\start.sh) :
#!/bin/bash
export USERPROFILE=D:/my/real/homedir
...
And it works well for me.

**Comment by chorrylan** [comment]
I'm seeing this problem after upgrading to v1.6.1;   v1.5.0 worked happily with the same junction point in place.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
