### ISSUE TITLE
boot2docker should NOT require VT-X

### ISSUE THREAD

**Issue by RepublicOfAppsLLC** [boot2docker/windows-installer#96]
Hi,

Thanks for making boot2docker and this windows installer available, much appreciated!

I work at a studio developing backend services for VR gaming.  I'm trying to setup dockerized versions of our backend services so that our fronted VR developers can test against these services on their Windows boxes.

The problem is that Occulus and most VR headsets **REQUIRE** VT-X to be turned OFF for decent performance.  Whereas boot2docker and docker require it to be ON (by virtue of requiring it and also because they're 64-bit).

So we need a 32-bit version of boot2docker and docker to support any kind of Docker containers for VR development since most of the VR headsets require VT-X OFF and 64-bit docker/boot2docker require VT-X ON.

We need to test connecting to docker while the VR headset is running (to see the results of data returned from the dockerized services in the headset's HUD).

I don't know how to do this currently.

Please make a version of docker that is 32-bit and does not require VT-X.

This is a showstopper for us ...

Thanks!

**Comment by jeffreyroberts** [comment]
+1, VT-X required is getting in my way

**Comment by SvenDowideit** [comment]
Boot2Docker uses the official releases of Docker - and Docker is not supported on 32bit Linux at this point - and thus, `any kind of Docker container` will mostly contain 64bit binaries. (Yes, I'm aware of the 32bit i86 and arm projects, but havn't had time to to more than play)

For this to happen, in boot2docker itself, much more continuous testing and infrastructure is required than we have now - we'd all welcome this, but its not at the top of the list.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
