### ISSUE TITLE
docker daemon not running on first boot after install.

### ISSUE THREAD

**Issue by oodgaard** [boot2docker/windows-installer#99]
Just booted up boot2docker 1.5.0. The initial boot hinted that the docker daemon was not running. Had to run boot2docker stop then start to fix it.

**Comment by tianon** [comment]
Sorry, this repository is long-since deprecated in favor of [Docker Toolbox](https://github.com/docker/toolbox) (whose usage is now also discouraged in favor of [Docker for Windows](https://www.docker.com/docker-windows) and [Docker for Mac](https://www.docker.com/docker-mac)).
